name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push backend
      run: |
        docker build -t your-dockerhub-username/bitcoin-explorer-backend ./backend
        docker push your-dockerhub-username/bitcoin-explorer-backend

    - name: Build and push frontend
      run: |
        docker build -t your-dockerhub-username/bitcoin-explorer-frontend ./frontend
        docker push your-dockerhub-username/bitcoin-explorer-frontend
